stages:
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 10
notification:
  recipients:
  - recipient: dan@mail.atriarch.systems
    notifier: c-xc9r9:n-g2gcc
  condition:
  - Failed
